---
apiVersion: traefik.io/v1alpha1  # Change from traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: error-pages-ingressroute
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`{host:.+}`)
      priority: 105
      services:
        - kind: Service
          name: error-pages
          port: 8080
      middlewares:
        - name: error-pages-middleware
