---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: error-pages-ingressroute
  namespace: error-pages
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(\`/\`)
      kind: Rule
      priority: 100
      services:
        - name: error-pages
          port: 8080
